<main class="d-flex flex-column">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb m-0">
        <li class="breadcrumb-item">Administration</li>
        <li class="breadcrumb-item active" aria-current="page">Gestion des auteurs</li>
    </ol>
  </nav>
  <div class="flex-grow-1 d-md-flex align-items-stretch">
    <?php include 'admin_menu.php'; ?>
    <section class="col-md-8 p-5 mx-auto">
      <header class="jumbotron text-center">
          <h2 class="text-center mb-4 display-4">Gestion des auteurs</h2>
      </header>
      <nav class="mb-4">
        <a class="btn btn-primary" href="#">
          <i class="fas fa-plus" aria-hidden="true"></i>
          Ajouter un auteur
        </a>
      </nav>
      <table class="table table-striped">
        <caption>Liste des auteurs</caption>
        <thead class="thead-dark">
          <tr>
            <th>ID</th>
            <th>Auteur</th>
            <th>Nombre d'articles</th>
            <th>Modifier</th>
            <th>Supprimer</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ( $authors as $author ): ?>
          <tr>
            <td><?= intval( $author['Id']) ?></td>
            <td><?= htmlspecialchars( $author['FirstName'] ) ?> <?= htmlspecialchars( $author['LastName'] ) ?></td>
            <td><?= htmlspecialchars( $author['Total'] ) ?></td>
            <td>
              <a
                class="btn btn-warning"
                title="Modifier"
                href="#">
                <i class="fa fa-pen-nib" aria-hidden="true"></i>
              </a>
            </td>
            <td>
              <?php if( $author['Total'] <= 0 ) : ?>
              <a href="#" class="btn btn-danger" title="Supprimer">
                <i class="fa fa-trash" aria-hidden="true"></i>
              </a>
              <?php endif; ?>
            </td>
          </tr>
        <?php endforeach; ?>
        </tbody>
      </table>
    </section>
  </div>
</main>
