<section id="gestion">
    <?php include 'admin_menu.php'?>
          <div id="edit">
              
            <h2>Mise à jour d'un article</h2><br><br>

            <form method="POST" action="admin_update.php?id=<?=$value['Id']?>">
                <label>Catégorie de l'article</label>
                <select name="category">
                  <?php foreach($categories as $categorie):?>
                    <option value="<?=$categorie['Id']?>" 
                    <?php if ($categorie['Id'] == $value['Category_Id']):?>
                    selected <?php endif;?>> <?=$categorie['Name']?></option>
                  <?php endforeach;?> 
                </select>

                <label>Auteur</label>

                <select name="author">                 
                  <?php foreach($auteurs as $auteur):?>
                    <option value="<?=$auteur['Id']?>" 
                    <?php if ($auteur['Id'] == $value['Author_Id']):?>
                    selected <?php endif;?>><?=$auteur['FirstName']?> <?=$auteur['LastName']?></option>
                  <?php endforeach;?>
                </select> <br><br>

                <label>Titre de l'article</label><br>
                <input type="text" name="title" value="<?=$value['Title']?>"><br><br><br>
                <label>Texte de l'article</label>
                <textarea cols="20" rows="8" name="content"><?=$value['Contents']?></textarea><br><br><br>

                <button >  Enregistrer </button>
            </form>

          </div>
    </section>