<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/9b99b32647.js" crossorigin="anonymous"></script>
    <title>Blog</title>

    <link rel="stylesheet" type="text/css" href="CSS/style.css">
    <link rel="stylesheet" type="text/css" href="CSS/normalize.css">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="js/ajax.js"> </script>
    <script src="js/events.js"> </script>
</head>
<body>

    <header>
        <nav id="navbar">
            <h4><a href="index.php"> Le blog du Tante URSULE</a></h4>
            <p><i class="fas fa-pen-nib"></i> <a href="admin_posts_index.php">Administration</a></p>
        </nav>

    </header>

    <main>
        <?php include $template; ?>

    </main>

    
    <footer> 
        <img src="https://3wa.fr/wp-content/uploads/2020/01/cropped-big.png" alt="3wa" title="3WA">
        <p></p><a id="academy" href="#">3W academy</a> - PHP: module2- Formation deveoppeur Web- Tous droits réservés</p>
        <small>Cet exercice est mis à dispotion des stagiaires dans le cadre exlusif de leur apprentissage</small>

    </footer>
    <script src="js/main.js"> </script>
</body>
</html>